return {
    ACTIONS = {
        AOC_CLOSE_DIMENSON_CONTAINER = "Close",
        AOC_OPEN_DIMENSON_CONTAINER = "Open",
        CASTAOE = {
            DREADSWORD_SKILL_PARRY = "Block",
            DREADSWORD_SKILL_WAVE = "Shadow Cut",
            DREAD_LANTERN_START = "Absorb Miasma",
            DREAD_LANTERN_STOP = "Stop Absorbing",
        },
    },
    DREADSWORD_TALK = {
        ATTTALK = {
            "I will tear your soul apart",
            "It's a waste of beautiful suffering",
            "Oh, this is what I'm going to show you",
            "Give up extravagant hopes",
            "Fragile",
            "you should suffer",
        },
        TALK = {
            "Fear, more despair!",
            "Look them in the eye!",
            "Do not resist the darkness of destiny!",
            "You crave more death",
            "end it all",
            "Let raw killing rule you",
            "...",
            "Madness...",
        },
    },
    NAMES = {
        DREADSPEAR = "Dreadstone Spear",
        DREADSWORD = "Dreadstone Sword",
        DREAD_AXE = "Shroud Axe",
        DREAD_CLOAK = "Darknight Splint Mail",
        DREAD_LANTERN = "Shroud Lantern",
        DREAD_PICKAXE = "Dreadstone Pickaxe",
        KNIGHTMARE = "Knight",
        KNIGHTMARE_ALLEGIANCE = "Real name?",
        LUNAR_SPARK_BLADE = "Spark Blade",
        NIGHTMAREHAT = "Darknight Helm",
        WOODS_SHADELING = "Laboring Horror",
    },
    RECIPE_DESC = {
        DREADSPEAR = "TODO",
        DREADSWORD = "Bring the deepest despair to your enemies",
        DREAD_AXE = "TODO",
        DREAD_CLOAK = "TODO",
        DREAD_LANTERN = "A very hopeless looking lantern.",
        DREAD_PICKAXE = "It's very destructive, but you need to find a good angle.",
        LUNAR_SPARK_BLADE = "TODO",
        NIGHTMAREHAT = "TODO",
    },
    SKIN_DESCRIPTIONS = {
        night_edge = "Night's Edge",
    },
    SKIN_NAMES = {
        night_edge = "Night's Edge",
    },
}
